### ISSUE TITLE
Desenvolver documento de introdução ao problema e contexto.

### ISSUE THREAD

**Issue by hs1lva** [hs1lva/PageTurner#15]

**Comment by hs1lva** [comment]
Feito em Wiki. Rever.

**Comment by PRS10** [comment]
No mundo atual, onde existem varias formas de entretenimento a competir pela atenção das pessoas, o habito pela leitura foi esmorecendo. Um artigo recente publicado pelo jornal Expresso destaca uma realidade preocupante em Portugal: de acordo com um inquérito conduzido pela Fundação Gulbenkian e pelo Instituto de Ciências Sociais da Universidade de Lisboa, surpreendentes 61% dos portugueses não leram um único livro no último ano.  

Esta estatística é preocupante, para abordar esta lacuna e promover a comunidade de leitura, surge o projeto PageTurner. O PageTurner é uma plataforma online que dedicada a reunir e incentivar leitores de todas as partes, oferecendo um refugio virtual onde podem criar perfis, registar os seus livros, partilhar resumos. Além disso, a plataforma oferece recursos adicionais, como download de livros de domínio publico, recomendações personalizadas e a oportunidade de trocar livros entre os membros da comunidade.  

 

 
Link para o artigo.
https://amp.expresso.pt/cultura/2022-02-16-61-dos-portugueses-nao-leram-um-so-livro-no-ultimo-ano
