### ISSUE TITLE
Descrever a relevância do problema.

### ISSUE THREAD

**Issue by hs1lva** [hs1lva/PageTurner#16]

**Comment by hs1lva** [comment]
Feito em Wiki. Rever.

**Comment by PRS10** [comment]
A leitura desempenha um papel fundamental no desenvolvimento pessoal, educacional e cultural de indivíduos e comunidades. No entanto, apesar dos varios benefícios que a leitura oferece, está a competir com uma adicta concorrencia digital. O plataforma PageTurner pretende aproveitar o espaço digital para (re)inserir o habito de leitura.
