### ISSUE TITLE
Detalhar a motivação para a resolução do problema.

### ISSUE THREAD

**Issue by hs1lva** [hs1lva/PageTurner#17]

**Comment by hs1lva** [comment]
Feito em Wiki. Rever.

**Comment by PRS10** [comment]
A motivação para resolver o problema do declínio do hábito de leitura diante da concorrência digital é impulsionada pelo reconhecimento do poder transformador da leitura e a preocupação com as gerações futuras, pois a falta de interesse pela leitura pode comprometer o desenvolvimento intelectual e emocional das próximas gerações, acreditamos que irá por em causa o seu pensamento critico.
